// Code generated by go-swagger; DO NOT EDIT.

// Package restapi 运动识别系统
//
//  运动识别系统API
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//    - application/x-www-form-urlencoded
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
