// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// CreateSportItemOKCode is the HTTP code returned for type CreateSportItemOK
const CreateSportItemOKCode int = 200

/*CreateSportItemOK ok

swagger:response createSportItemOK
*/
type CreateSportItemOK struct {

	/*
	  In: Body
	*/
	Payload *v1.SportItem `json:"body,omitempty"`
}

// NewCreateSportItemOK creates CreateSportItemOK with default headers values
func NewCreateSportItemOK() *CreateSportItemOK {

	return &CreateSportItemOK{}
}

// WithPayload adds the payload to the create sport item o k response
func (o *CreateSportItemOK) WithPayload(payload *v1.SportItem) *CreateSportItemOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create sport item o k response
func (o *CreateSportItemOK) SetPayload(payload *v1.SportItem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSportItemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
