// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// CreateCommentHandlerFunc turns a function with the right signature into a create comment handler
type CreateCommentHandlerFunc func(CreateCommentParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCommentHandlerFunc) Handle(params CreateCommentParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateCommentHandler interface for that can handle valid create comment params
type CreateCommentHandler interface {
	Handle(CreateCommentParams, *v1.Principal) middleware.Responder
}

// NewCreateComment creates a new http.Handler for the create comment operation
func NewCreateComment(ctx *middleware.Context, handler CreateCommentHandler) *CreateComment {
	return &CreateComment{Context: ctx, Handler: handler}
}

/* CreateComment swagger:route POST /v1/comment monitor createComment

创建学生评论信息

创建评论信息

*/
type CreateComment struct {
	Context *middleware.Context
	Handler CreateCommentHandler
}

func (o *CreateComment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateCommentParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
