// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// CreateCourseOKCode is the HTTP code returned for type CreateCourseOK
const CreateCourseOKCode int = 200

/*CreateCourseOK ok

swagger:response createCourseOK
*/
type CreateCourseOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Course `json:"body,omitempty"`
}

// NewCreateCourseOK creates CreateCourseOK with default headers values
func NewCreateCourseOK() *CreateCourseOK {

	return &CreateCourseOK{}
}

// WithPayload adds the payload to the create course o k response
func (o *CreateCourseOK) WithPayload(payload *v1.Course) *CreateCourseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create course o k response
func (o *CreateCourseOK) SetPayload(payload *v1.Course) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCourseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
