// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// CreateSportItemHandlerFunc turns a function with the right signature into a create sport item handler
type CreateSportItemHandlerFunc func(CreateSportItemParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateSportItemHandlerFunc) Handle(params CreateSportItemParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateSportItemHandler interface for that can handle valid create sport item params
type CreateSportItemHandler interface {
	Handle(CreateSportItemParams, *v1.Principal) middleware.Responder
}

// NewCreateSportItem creates a new http.Handler for the create sport item operation
func NewCreateSportItem(ctx *middleware.Context, handler CreateSportItemHandler) *CreateSportItem {
	return &CreateSportItem{Context: ctx, Handler: handler}
}

/* CreateSportItem swagger:route POST /v1/sportItem monitor createSportItem

创建运动项目信息

创建运动项目信息

*/
type CreateSportItem struct {
	Context *middleware.Context
	Handler CreateSportItemHandler
}

func (o *CreateSportItem) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateSportItemParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
