// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// CreateEvaluateInfoHandlerFunc turns a function with the right signature into a create evaluate info handler
type CreateEvaluateInfoHandlerFunc func(CreateEvaluateInfoParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateEvaluateInfoHandlerFunc) Handle(params CreateEvaluateInfoParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateEvaluateInfoHandler interface for that can handle valid create evaluate info params
type CreateEvaluateInfoHandler interface {
	Handle(CreateEvaluateInfoParams, *v1.Principal) middleware.Responder
}

// NewCreateEvaluateInfo creates a new http.Handler for the create evaluate info operation
func NewCreateEvaluateInfo(ctx *middleware.Context, handler CreateEvaluateInfoHandler) *CreateEvaluateInfo {
	return &CreateEvaluateInfo{Context: ctx, Handler: handler}
}

/* CreateEvaluateInfo swagger:route POST /v1/evaluateInfo monitor createEvaluateInfo

创建评价信息

创建评价信息

*/
type CreateEvaluateInfo struct {
	Context *middleware.Context
	Handler CreateEvaluateInfoHandler
}

func (o *CreateEvaluateInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateEvaluateInfoParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
