// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// CreateCourseHandlerFunc turns a function with the right signature into a create course handler
type CreateCourseHandlerFunc func(CreateCourseParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCourseHandlerFunc) Handle(params CreateCourseParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateCourseHandler interface for that can handle valid create course params
type CreateCourseHandler interface {
	Handle(CreateCourseParams, *v1.Principal) middleware.Responder
}

// NewCreateCourse creates a new http.Handler for the create course operation
func NewCreateCourse(ctx *middleware.Context, handler CreateCourseHandler) *CreateCourse {
	return &CreateCourse{Context: ctx, Handler: handler}
}

/* CreateCourse swagger:route POST /v1/course monitor createCourse

创建课程信息

创建课程信息

*/
type CreateCourse struct {
	Context *middleware.Context
	Handler CreateCourseHandler
}

func (o *CreateCourse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateCourseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
