// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// CreateSportTypeOKCode is the HTTP code returned for type CreateSportTypeOK
const CreateSportTypeOKCode int = 200

/*CreateSportTypeOK ok

swagger:response createSportTypeOK
*/
type CreateSportTypeOK struct {

	/*
	  In: Body
	*/
	Payload *v1.SportType `json:"body,omitempty"`
}

// NewCreateSportTypeOK creates CreateSportTypeOK with default headers values
func NewCreateSportTypeOK() *CreateSportTypeOK {

	return &CreateSportTypeOK{}
}

// WithPayload adds the payload to the create sport type o k response
func (o *CreateSportTypeOK) WithPayload(payload *v1.SportType) *CreateSportTypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create sport type o k response
func (o *CreateSportTypeOK) SetPayload(payload *v1.SportType) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSportTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
