// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// DeleteHomeWorkOKCode is the HTTP code returned for type DeleteHomeWorkOK
const DeleteHomeWorkOKCode int = 200

/*DeleteHomeWorkOK A successful response.

swagger:response deleteHomeWorkOK
*/
type DeleteHomeWorkOK struct {

	/*
	  In: Body
	*/
	Payload *v1.HomeWork `json:"body,omitempty"`
}

// NewDeleteHomeWorkOK creates DeleteHomeWorkOK with default headers values
func NewDeleteHomeWorkOK() *DeleteHomeWorkOK {

	return &DeleteHomeWorkOK{}
}

// WithPayload adds the payload to the delete home work o k response
func (o *DeleteHomeWorkOK) WithPayload(payload *v1.HomeWork) *DeleteHomeWorkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete home work o k response
func (o *DeleteHomeWorkOK) SetPayload(payload *v1.HomeWork) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHomeWorkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
