// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// DeleteSportTypeOKCode is the HTTP code returned for type DeleteSportTypeOK
const DeleteSportTypeOKCode int = 200

/*DeleteSportTypeOK A successful response.

swagger:response deleteSportTypeOK
*/
type DeleteSportTypeOK struct {

	/*
	  In: Body
	*/
	Payload *v1.SportType `json:"body,omitempty"`
}

// NewDeleteSportTypeOK creates DeleteSportTypeOK with default headers values
func NewDeleteSportTypeOK() *DeleteSportTypeOK {

	return &DeleteSportTypeOK{}
}

// WithPayload adds the payload to the delete sport type o k response
func (o *DeleteSportTypeOK) WithPayload(payload *v1.SportType) *DeleteSportTypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete sport type o k response
func (o *DeleteSportTypeOK) SetPayload(payload *v1.SportType) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSportTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
