// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// DeleteSportItemOKCode is the HTTP code returned for type DeleteSportItemOK
const DeleteSportItemOKCode int = 200

/*DeleteSportItemOK A successful response.

swagger:response deleteSportItemOK
*/
type DeleteSportItemOK struct {

	/*
	  In: Body
	*/
	Payload *v1.SportItem `json:"body,omitempty"`
}

// NewDeleteSportItemOK creates DeleteSportItemOK with default headers values
func NewDeleteSportItemOK() *DeleteSportItemOK {

	return &DeleteSportItemOK{}
}

// WithPayload adds the payload to the delete sport item o k response
func (o *DeleteSportItemOK) WithPayload(payload *v1.SportItem) *DeleteSportItemOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete sport item o k response
func (o *DeleteSportItemOK) SetPayload(payload *v1.SportItem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSportItemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
