// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// DeleteEvaluateInfoOKCode is the HTTP code returned for type DeleteEvaluateInfoOK
const DeleteEvaluateInfoOKCode int = 200

/*DeleteEvaluateInfoOK A successful response.

swagger:response deleteEvaluateInfoOK
*/
type DeleteEvaluateInfoOK struct {

	/*
	  In: Body
	*/
	Payload *v1.EvaluateInfo `json:"body,omitempty"`
}

// NewDeleteEvaluateInfoOK creates DeleteEvaluateInfoOK with default headers values
func NewDeleteEvaluateInfoOK() *DeleteEvaluateInfoOK {

	return &DeleteEvaluateInfoOK{}
}

// WithPayload adds the payload to the delete evaluate info o k response
func (o *DeleteEvaluateInfoOK) WithPayload(payload *v1.EvaluateInfo) *DeleteEvaluateInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete evaluate info o k response
func (o *DeleteEvaluateInfoOK) SetPayload(payload *v1.EvaluateInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteEvaluateInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
