// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// DeleteSolutionOKCode is the HTTP code returned for type DeleteSolutionOK
const DeleteSolutionOKCode int = 200

/*DeleteSolutionOK A successful response.

swagger:response deleteSolutionOK
*/
type DeleteSolutionOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Solution `json:"body,omitempty"`
}

// NewDeleteSolutionOK creates DeleteSolutionOK with default headers values
func NewDeleteSolutionOK() *DeleteSolutionOK {

	return &DeleteSolutionOK{}
}

// WithPayload adds the payload to the delete solution o k response
func (o *DeleteSolutionOK) WithPayload(payload *v1.Solution) *DeleteSolutionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete solution o k response
func (o *DeleteSolutionOK) SetPayload(payload *v1.Solution) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSolutionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
