// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// DeleteCourseOKCode is the HTTP code returned for type DeleteCourseOK
const DeleteCourseOKCode int = 200

/*DeleteCourseOK A successful response.

swagger:response deleteCourseOK
*/
type DeleteCourseOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Course `json:"body,omitempty"`
}

// NewDeleteCourseOK creates DeleteCourseOK with default headers values
func NewDeleteCourseOK() *DeleteCourseOK {

	return &DeleteCourseOK{}
}

// WithPayload adds the payload to the delete course o k response
func (o *DeleteCourseOK) WithPayload(payload *v1.Course) *DeleteCourseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete course o k response
func (o *DeleteCourseOK) SetPayload(payload *v1.Course) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCourseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
