// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// DeleteSportItemHandlerFunc turns a function with the right signature into a delete sport item handler
type DeleteSportItemHandlerFunc func(DeleteSportItemParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSportItemHandlerFunc) Handle(params DeleteSportItemParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteSportItemHandler interface for that can handle valid delete sport item params
type DeleteSportItemHandler interface {
	Handle(DeleteSportItemParams, *v1.Principal) middleware.Responder
}

// NewDeleteSportItem creates a new http.Handler for the delete sport item operation
func NewDeleteSportItem(ctx *middleware.Context, handler DeleteSportItemHandler) *DeleteSportItem {
	return &DeleteSportItem{Context: ctx, Handler: handler}
}

/* DeleteSportItem swagger:route DELETE /v1/sportItem/{id} monitor deleteSportItem

删除运动项目信息

删除运动项目信息

*/
type DeleteSportItem struct {
	Context *middleware.Context
	Handler DeleteSportItemHandler
}

func (o *DeleteSportItem) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteSportItemParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
