// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// DeleteCommentHandlerFunc turns a function with the right signature into a delete comment handler
type DeleteCommentHandlerFunc func(DeleteCommentParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCommentHandlerFunc) Handle(params DeleteCommentParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteCommentHandler interface for that can handle valid delete comment params
type DeleteCommentHandler interface {
	Handle(DeleteCommentParams, *v1.Principal) middleware.Responder
}

// NewDeleteComment creates a new http.Handler for the delete comment operation
func NewDeleteComment(ctx *middleware.Context, handler DeleteCommentHandler) *DeleteComment {
	return &DeleteComment{Context: ctx, Handler: handler}
}

/* DeleteComment swagger:route DELETE /v1/comment/{id} monitor deleteComment

删除学生提交信息

删除评论信息

*/
type DeleteComment struct {
	Context *middleware.Context
	Handler DeleteCommentHandler
}

func (o *DeleteComment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteCommentParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
