// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetCommentsHandlerFunc turns a function with the right signature into a get comments handler
type GetCommentsHandlerFunc func(GetCommentsParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCommentsHandlerFunc) Handle(params GetCommentsParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetCommentsHandler interface for that can handle valid get comments params
type GetCommentsHandler interface {
	Handle(GetCommentsParams, *v1.Principal) middleware.Responder
}

// NewGetComments creates a new http.Handler for the get comments operation
func NewGetComments(ctx *middleware.Context, handler GetCommentsHandler) *GetComments {
	return &GetComments{Context: ctx, Handler: handler}
}

/* GetComments swagger:route GET /v1/Comments monitor getComments

获取学生评论信息列表

获取评论信息列表

*/
type GetComments struct {
	Context *middleware.Context
	Handler GetCommentsHandler
}

func (o *GetComments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCommentsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
