// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetCourseOKCode is the HTTP code returned for type GetCourseOK
const GetCourseOKCode int = 200

/*GetCourseOK A successful response.

swagger:response getCourseOK
*/
type GetCourseOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Course `json:"body,omitempty"`
}

// NewGetCourseOK creates GetCourseOK with default headers values
func NewGetCourseOK() *GetCourseOK {

	return &GetCourseOK{}
}

// WithPayload adds the payload to the get course o k response
func (o *GetCourseOK) WithPayload(payload *v1.Course) *GetCourseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get course o k response
func (o *GetCourseOK) SetPayload(payload *v1.Course) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCourseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
