// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetHomeWorksHandlerFunc turns a function with the right signature into a get home works handler
type GetHomeWorksHandlerFunc func(GetHomeWorksParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHomeWorksHandlerFunc) Handle(params GetHomeWorksParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetHomeWorksHandler interface for that can handle valid get home works params
type GetHomeWorksHandler interface {
	Handle(GetHomeWorksParams, *v1.Principal) middleware.Responder
}

// NewGetHomeWorks creates a new http.Handler for the get home works operation
func NewGetHomeWorks(ctx *middleware.Context, handler GetHomeWorksHandler) *GetHomeWorks {
	return &GetHomeWorks{Context: ctx, Handler: handler}
}

/* GetHomeWorks swagger:route GET /v1/homeWorks monitor getHomeWorks

获取作业信息列表

获取作业信息列表

*/
type GetHomeWorks struct {
	Context *middleware.Context
	Handler GetHomeWorksHandler
}

func (o *GetHomeWorks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetHomeWorksParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
