// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetSportItemsOKCode is the HTTP code returned for type GetSportItemsOK
const GetSportItemsOKCode int = 200

/*GetSportItemsOK ok

swagger:response getSportItemsOK
*/
type GetSportItemsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.SportItems `json:"body,omitempty"`
}

// NewGetSportItemsOK creates GetSportItemsOK with default headers values
func NewGetSportItemsOK() *GetSportItemsOK {

	return &GetSportItemsOK{}
}

// WithPayload adds the payload to the get sport items o k response
func (o *GetSportItemsOK) WithPayload(payload *v1.SportItems) *GetSportItemsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sport items o k response
func (o *GetSportItemsOK) SetPayload(payload *v1.SportItems) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSportItemsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
