// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetCommentsOKCode is the HTTP code returned for type GetCommentsOK
const GetCommentsOKCode int = 200

/*GetCommentsOK ok

swagger:response getCommentsOK
*/
type GetCommentsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Comments `json:"body,omitempty"`
}

// NewGetCommentsOK creates GetCommentsOK with default headers values
func NewGetCommentsOK() *GetCommentsOK {

	return &GetCommentsOK{}
}

// WithPayload adds the payload to the get comments o k response
func (o *GetCommentsOK) WithPayload(payload *v1.Comments) *GetCommentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get comments o k response
func (o *GetCommentsOK) SetPayload(payload *v1.Comments) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
