// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetCourseHandlerFunc turns a function with the right signature into a get course handler
type GetCourseHandlerFunc func(GetCourseParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCourseHandlerFunc) Handle(params GetCourseParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetCourseHandler interface for that can handle valid get course params
type GetCourseHandler interface {
	Handle(GetCourseParams, *v1.Principal) middleware.Responder
}

// NewGetCourse creates a new http.Handler for the get course operation
func NewGetCourse(ctx *middleware.Context, handler GetCourseHandler) *GetCourse {
	return &GetCourse{Context: ctx, Handler: handler}
}

/* GetCourse swagger:route GET /v1/course/{id} monitor getCourse

获取课程信息

获取课程信息

*/
type GetCourse struct {
	Context *middleware.Context
	Handler GetCourseHandler
}

func (o *GetCourse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCourseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
