// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetSolutionOKCode is the HTTP code returned for type GetSolutionOK
const GetSolutionOKCode int = 200

/*GetSolutionOK A successful response.

swagger:response getSolutionOK
*/
type GetSolutionOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Solution `json:"body,omitempty"`
}

// NewGetSolutionOK creates GetSolutionOK with default headers values
func NewGetSolutionOK() *GetSolutionOK {

	return &GetSolutionOK{}
}

// WithPayload adds the payload to the get solution o k response
func (o *GetSolutionOK) WithPayload(payload *v1.Solution) *GetSolutionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get solution o k response
func (o *GetSolutionOK) SetPayload(payload *v1.Solution) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSolutionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
