// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetSportItemOKCode is the HTTP code returned for type GetSportItemOK
const GetSportItemOKCode int = 200

/*GetSportItemOK A successful response.

swagger:response getSportItemOK
*/
type GetSportItemOK struct {

	/*
	  In: Body
	*/
	Payload *v1.SportItem `json:"body,omitempty"`
}

// NewGetSportItemOK creates GetSportItemOK with default headers values
func NewGetSportItemOK() *GetSportItemOK {

	return &GetSportItemOK{}
}

// WithPayload adds the payload to the get sport item o k response
func (o *GetSportItemOK) WithPayload(payload *v1.SportItem) *GetSportItemOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sport item o k response
func (o *GetSportItemOK) SetPayload(payload *v1.SportItem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSportItemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
