// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetSportTypeOKCode is the HTTP code returned for type GetSportTypeOK
const GetSportTypeOKCode int = 200

/*GetSportTypeOK A successful response.

swagger:response getSportTypeOK
*/
type GetSportTypeOK struct {

	/*
	  In: Body
	*/
	Payload *v1.SportType `json:"body,omitempty"`
}

// NewGetSportTypeOK creates GetSportTypeOK with default headers values
func NewGetSportTypeOK() *GetSportTypeOK {

	return &GetSportTypeOK{}
}

// WithPayload adds the payload to the get sport type o k response
func (o *GetSportTypeOK) WithPayload(payload *v1.SportType) *GetSportTypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sport type o k response
func (o *GetSportTypeOK) SetPayload(payload *v1.SportType) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSportTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
