// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetHomeWorkOKCode is the HTTP code returned for type GetHomeWorkOK
const GetHomeWorkOKCode int = 200

/*GetHomeWorkOK A successful response.

swagger:response getHomeWorkOK
*/
type GetHomeWorkOK struct {

	/*
	  In: Body
	*/
	Payload *v1.HomeWork `json:"body,omitempty"`
}

// NewGetHomeWorkOK creates GetHomeWorkOK with default headers values
func NewGetHomeWorkOK() *GetHomeWorkOK {

	return &GetHomeWorkOK{}
}

// WithPayload adds the payload to the get home work o k response
func (o *GetHomeWorkOK) WithPayload(payload *v1.HomeWork) *GetHomeWorkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get home work o k response
func (o *GetHomeWorkOK) SetPayload(payload *v1.HomeWork) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHomeWorkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
