// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetSolutionHandlerFunc turns a function with the right signature into a get solution handler
type GetSolutionHandlerFunc func(GetSolutionParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSolutionHandlerFunc) Handle(params GetSolutionParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetSolutionHandler interface for that can handle valid get solution params
type GetSolutionHandler interface {
	Handle(GetSolutionParams, *v1.Principal) middleware.Responder
}

// NewGetSolution creates a new http.Handler for the get solution operation
func NewGetSolution(ctx *middleware.Context, handler GetSolutionHandler) *GetSolution {
	return &GetSolution{Context: ctx, Handler: handler}
}

/* GetSolution swagger:route GET /v1/solution/{id} monitor getSolution

获取学生提交作业信息

获取学生提交作业信息

*/
type GetSolution struct {
	Context *middleware.Context
	Handler GetSolutionHandler
}

func (o *GetSolution) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSolutionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
