// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetCommentHandlerFunc turns a function with the right signature into a get comment handler
type GetCommentHandlerFunc func(GetCommentParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCommentHandlerFunc) Handle(params GetCommentParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetCommentHandler interface for that can handle valid get comment params
type GetCommentHandler interface {
	Handle(GetCommentParams, *v1.Principal) middleware.Responder
}

// NewGetComment creates a new http.Handler for the get comment operation
func NewGetComment(ctx *middleware.Context, handler GetCommentHandler) *GetComment {
	return &GetComment{Context: ctx, Handler: handler}
}

/* GetComment swagger:route GET /v1/comment/{id} monitor getComment

学生评论信息

获取评论信息

*/
type GetComment struct {
	Context *middleware.Context
	Handler GetCommentHandler
}

func (o *GetComment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCommentParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
