// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetSolutionsOKCode is the HTTP code returned for type GetSolutionsOK
const GetSolutionsOKCode int = 200

/*GetSolutionsOK ok

swagger:response getSolutionsOK
*/
type GetSolutionsOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Solutions `json:"body,omitempty"`
}

// NewGetSolutionsOK creates GetSolutionsOK with default headers values
func NewGetSolutionsOK() *GetSolutionsOK {

	return &GetSolutionsOK{}
}

// WithPayload adds the payload to the get solutions o k response
func (o *GetSolutionsOK) WithPayload(payload *v1.Solutions) *GetSolutionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get solutions o k response
func (o *GetSolutionsOK) SetPayload(payload *v1.Solutions) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSolutionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
