// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetSportItemsHandlerFunc turns a function with the right signature into a get sport items handler
type GetSportItemsHandlerFunc func(GetSportItemsParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSportItemsHandlerFunc) Handle(params GetSportItemsParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetSportItemsHandler interface for that can handle valid get sport items params
type GetSportItemsHandler interface {
	Handle(GetSportItemsParams, *v1.Principal) middleware.Responder
}

// NewGetSportItems creates a new http.Handler for the get sport items operation
func NewGetSportItems(ctx *middleware.Context, handler GetSportItemsHandler) *GetSportItems {
	return &GetSportItems{Context: ctx, Handler: handler}
}

/* GetSportItems swagger:route GET /v1/sportItems monitor getSportItems

获取运动项目信息列表

获取运动项目信息列表

*/
type GetSportItems struct {
	Context *middleware.Context
	Handler GetSportItemsHandler
}

func (o *GetSportItems) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSportItemsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
