// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetCommentOKCode is the HTTP code returned for type GetCommentOK
const GetCommentOKCode int = 200

/*GetCommentOK A successful response.

swagger:response getCommentOK
*/
type GetCommentOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Comment `json:"body,omitempty"`
}

// NewGetCommentOK creates GetCommentOK with default headers values
func NewGetCommentOK() *GetCommentOK {

	return &GetCommentOK{}
}

// WithPayload adds the payload to the get comment o k response
func (o *GetCommentOK) WithPayload(payload *v1.Comment) *GetCommentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get comment o k response
func (o *GetCommentOK) SetPayload(payload *v1.Comment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
