// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetHomeWorksOKCode is the HTTP code returned for type GetHomeWorksOK
const GetHomeWorksOKCode int = 200

/*GetHomeWorksOK ok

swagger:response getHomeWorksOK
*/
type GetHomeWorksOK struct {

	/*
	  In: Body
	*/
	Payload *v1.HomeWorks `json:"body,omitempty"`
}

// NewGetHomeWorksOK creates GetHomeWorksOK with default headers values
func NewGetHomeWorksOK() *GetHomeWorksOK {

	return &GetHomeWorksOK{}
}

// WithPayload adds the payload to the get home works o k response
func (o *GetHomeWorksOK) WithPayload(payload *v1.HomeWorks) *GetHomeWorksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get home works o k response
func (o *GetHomeWorksOK) SetPayload(payload *v1.HomeWorks) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHomeWorksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
