// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetSportTypeHandlerFunc turns a function with the right signature into a get sport type handler
type GetSportTypeHandlerFunc func(GetSportTypeParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSportTypeHandlerFunc) Handle(params GetSportTypeParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetSportTypeHandler interface for that can handle valid get sport type params
type GetSportTypeHandler interface {
	Handle(GetSportTypeParams, *v1.Principal) middleware.Responder
}

// NewGetSportType creates a new http.Handler for the get sport type operation
func NewGetSportType(ctx *middleware.Context, handler GetSportTypeHandler) *GetSportType {
	return &GetSportType{Context: ctx, Handler: handler}
}

/* GetSportType swagger:route GET /v1/sportType/{id} monitor getSportType

获取运动类别

获取运动类别

*/
type GetSportType struct {
	Context *middleware.Context
	Handler GetSportTypeHandler
}

func (o *GetSportType) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSportTypeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
