// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// UpdateSolutionHandlerFunc turns a function with the right signature into a update solution handler
type UpdateSolutionHandlerFunc func(UpdateSolutionParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSolutionHandlerFunc) Handle(params UpdateSolutionParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateSolutionHandler interface for that can handle valid update solution params
type UpdateSolutionHandler interface {
	Handle(UpdateSolutionParams, *v1.Principal) middleware.Responder
}

// NewUpdateSolution creates a new http.Handler for the update solution operation
func NewUpdateSolution(ctx *middleware.Context, handler UpdateSolutionHandler) *UpdateSolution {
	return &UpdateSolution{Context: ctx, Handler: handler}
}

/* UpdateSolution swagger:route PUT /v1/solution/{id} monitor updateSolution

编辑学生提交作业信息

编辑学生提交作业信息

*/
type UpdateSolution struct {
	Context *middleware.Context
	Handler UpdateSolutionHandler
}

func (o *UpdateSolution) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateSolutionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
