// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// UpdateSportTypeOKCode is the HTTP code returned for type UpdateSportTypeOK
const UpdateSportTypeOKCode int = 200

/*UpdateSportTypeOK A successful response.

swagger:response updateSportTypeOK
*/
type UpdateSportTypeOK struct {

	/*
	  In: Body
	*/
	Payload *v1.SportType `json:"body,omitempty"`
}

// NewUpdateSportTypeOK creates UpdateSportTypeOK with default headers values
func NewUpdateSportTypeOK() *UpdateSportTypeOK {

	return &UpdateSportTypeOK{}
}

// WithPayload adds the payload to the update sport type o k response
func (o *UpdateSportTypeOK) WithPayload(payload *v1.SportType) *UpdateSportTypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update sport type o k response
func (o *UpdateSportTypeOK) SetPayload(payload *v1.SportType) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSportTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
