// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// UpdateHomeWorkHandlerFunc turns a function with the right signature into a update home work handler
type UpdateHomeWorkHandlerFunc func(UpdateHomeWorkParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateHomeWorkHandlerFunc) Handle(params UpdateHomeWorkParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateHomeWorkHandler interface for that can handle valid update home work params
type UpdateHomeWorkHandler interface {
	Handle(UpdateHomeWorkParams, *v1.Principal) middleware.Responder
}

// NewUpdateHomeWork creates a new http.Handler for the update home work operation
func NewUpdateHomeWork(ctx *middleware.Context, handler UpdateHomeWorkHandler) *UpdateHomeWork {
	return &UpdateHomeWork{Context: ctx, Handler: handler}
}

/* UpdateHomeWork swagger:route PUT /v1/homeWork/{id} monitor updateHomeWork

编辑作业信息

编辑作业信息

*/
type UpdateHomeWork struct {
	Context *middleware.Context
	Handler UpdateHomeWorkHandler
}

func (o *UpdateHomeWork) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateHomeWorkParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
