// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// UpdateCommentOKCode is the HTTP code returned for type UpdateCommentOK
const UpdateCommentOKCode int = 200

/*UpdateCommentOK A successful response.

swagger:response updateCommentOK
*/
type UpdateCommentOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Comment `json:"body,omitempty"`
}

// NewUpdateCommentOK creates UpdateCommentOK with default headers values
func NewUpdateCommentOK() *UpdateCommentOK {

	return &UpdateCommentOK{}
}

// WithPayload adds the payload to the update comment o k response
func (o *UpdateCommentOK) WithPayload(payload *v1.Comment) *UpdateCommentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update comment o k response
func (o *UpdateCommentOK) SetPayload(payload *v1.Comment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCommentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
