// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// UpdateEvaluateInfoOKCode is the HTTP code returned for type UpdateEvaluateInfoOK
const UpdateEvaluateInfoOKCode int = 200

/*UpdateEvaluateInfoOK A successful response.

swagger:response updateEvaluateInfoOK
*/
type UpdateEvaluateInfoOK struct {

	/*
	  In: Body
	*/
	Payload *v1.EvaluateInfo `json:"body,omitempty"`
}

// NewUpdateEvaluateInfoOK creates UpdateEvaluateInfoOK with default headers values
func NewUpdateEvaluateInfoOK() *UpdateEvaluateInfoOK {

	return &UpdateEvaluateInfoOK{}
}

// WithPayload adds the payload to the update evaluate info o k response
func (o *UpdateEvaluateInfoOK) WithPayload(payload *v1.EvaluateInfo) *UpdateEvaluateInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update evaluate info o k response
func (o *UpdateEvaluateInfoOK) SetPayload(payload *v1.EvaluateInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateEvaluateInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
