// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// UpdateCourseOKCode is the HTTP code returned for type UpdateCourseOK
const UpdateCourseOKCode int = 200

/*UpdateCourseOK A successful response.

swagger:response updateCourseOK
*/
type UpdateCourseOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Course `json:"body,omitempty"`
}

// NewUpdateCourseOK creates UpdateCourseOK with default headers values
func NewUpdateCourseOK() *UpdateCourseOK {

	return &UpdateCourseOK{}
}

// WithPayload adds the payload to the update course o k response
func (o *UpdateCourseOK) WithPayload(payload *v1.Course) *UpdateCourseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update course o k response
func (o *UpdateCourseOK) SetPayload(payload *v1.Course) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCourseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
