// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// UpdateHomeWorkOKCode is the HTTP code returned for type UpdateHomeWorkOK
const UpdateHomeWorkOKCode int = 200

/*UpdateHomeWorkOK A successful response.

swagger:response updateHomeWorkOK
*/
type UpdateHomeWorkOK struct {

	/*
	  In: Body
	*/
	Payload *v1.HomeWork `json:"body,omitempty"`
}

// NewUpdateHomeWorkOK creates UpdateHomeWorkOK with default headers values
func NewUpdateHomeWorkOK() *UpdateHomeWorkOK {

	return &UpdateHomeWorkOK{}
}

// WithPayload adds the payload to the update home work o k response
func (o *UpdateHomeWorkOK) WithPayload(payload *v1.HomeWork) *UpdateHomeWorkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update home work o k response
func (o *UpdateHomeWorkOK) SetPayload(payload *v1.HomeWork) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHomeWorkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
