// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// UpdateCourseHandlerFunc turns a function with the right signature into a update course handler
type UpdateCourseHandlerFunc func(UpdateCourseParams, *v1.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateCourseHandlerFunc) Handle(params UpdateCourseParams, principal *v1.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateCourseHandler interface for that can handle valid update course params
type UpdateCourseHandler interface {
	Handle(UpdateCourseParams, *v1.Principal) middleware.Responder
}

// NewUpdateCourse creates a new http.Handler for the update course operation
func NewUpdateCourse(ctx *middleware.Context, handler UpdateCourseHandler) *UpdateCourse {
	return &UpdateCourse{Context: ctx, Handler: handler}
}

/* UpdateCourse swagger:route PUT /v1/course/{id} monitor updateCourse

编辑课程信息

编辑课程信息

*/
type UpdateCourse struct {
	Context *middleware.Context
	Handler UpdateCourseHandler
}

func (o *UpdateCourse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateCourseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *v1.Principal
	if uprinc != nil {
		principal = uprinc.(*v1.Principal) // this is really a v1.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
