// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// GetPhoneNumberOKCode is the HTTP code returned for type GetPhoneNumberOK
const GetPhoneNumberOKCode int = 200

/*GetPhoneNumberOK A successful response.

swagger:response getPhoneNumberOK
*/
type GetPhoneNumberOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Phone `json:"body,omitempty"`
}

// NewGetPhoneNumberOK creates GetPhoneNumberOK with default headers values
func NewGetPhoneNumberOK() *GetPhoneNumberOK {

	return &GetPhoneNumberOK{}
}

// WithPayload adds the payload to the get phone number o k response
func (o *GetPhoneNumberOK) WithPayload(payload *v1.Phone) *GetPhoneNumberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get phone number o k response
func (o *GetPhoneNumberOK) SetPayload(payload *v1.Phone) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPhoneNumberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
