// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WXLoginHandlerFunc turns a function with the right signature into a w x login handler
type WXLoginHandlerFunc func(WXLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn WXLoginHandlerFunc) Handle(params WXLoginParams) middleware.Responder {
	return fn(params)
}

// WXLoginHandler interface for that can handle valid w x login params
type WXLoginHandler interface {
	Handle(WXLoginParams) middleware.Responder
}

// NewWXLogin creates a new http.Handler for the w x login operation
func NewWXLogin(ctx *middleware.Context, handler WXLoginHandler) *WXLogin {
	return &WXLogin{Context: ctx, Handler: handler}
}

/* WXLogin swagger:route GET /v1/wx/login user wXLogin

小程序用户登录

小程序用户登录

*/
type WXLogin struct {
	Context *middleware.Context
	Handler WXLoginHandler
}

func (o *WXLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewWXLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
