// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	v1 "github.com/yushk/sport_backend/apiserver/v1"
)

// WXLoginOKCode is the HTTP code returned for type WXLoginOK
const WXLoginOKCode int = 200

/*WXLoginOK A successful response.

swagger:response wXLoginOK
*/
type WXLoginOK struct {

	/*
	  In: Body
	*/
	Payload *v1.Token `json:"body,omitempty"`
}

// NewWXLoginOK creates WXLoginOK with default headers values
func NewWXLoginOK() *WXLoginOK {

	return &WXLoginOK{}
}

// WithPayload adds the payload to the w x login o k response
func (o *WXLoginOK) WithPayload(payload *v1.Token) *WXLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the w x login o k response
func (o *WXLoginOK) SetPayload(payload *v1.Token) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WXLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
