// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Evaluate 评价体系列表
//
// swagger:model Evaluate
type Evaluate struct {

	// 优秀
	Excellent string `json:"excellent"`

	// 不及格
	Flunk string `json:"flunk"`

	// 良好
	Good string `json:"good"`

	// id
	// Read Only: true
	ID string `json:"id"`

	// 名称
	Name string `json:"name"`

	// 及格
	Pass string `json:"pass"`
}

// Validate validates this evaluate
func (m *Evaluate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this evaluate based on the context it is used
func (m *Evaluate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Evaluate) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Evaluate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Evaluate) UnmarshalBinary(b []byte) error {
	var res Evaluate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
