// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NoteInfo 作业打分信息列表
//
// swagger:model NoteInfo
type NoteInfo struct {

	// 内容
	Content string `json:"content"`

	// 打分
	Score string `json:"score"`

	// 状态
	Status string `json:"status"`

	// 学生id
	Userid string `json:"userid"`

	// 原始值
	Value string `json:"value"`
}

// Validate validates this note info
func (m *NoteInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this note info based on context it is used
func (m *NoteInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NoteInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NoteInfo) UnmarshalBinary(b []byte) error {
	var res NoteInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
